DROP TABLE IF EXISTS comments;

CREATE TABLE IF NOT EXISTS comments
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  content TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  image_key TEXT
);
